### PR TITLE
feat: Added support for `agent` option. [#78]

### PR DESCRIPTION
**Pull request by ShogunPanda**
This adds the `agent` option, which will be forward to `fetch`.

### CODE REVIEW

**Review by simoneb — APPROVED** [review]
LGTM, perfect 💯

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by simoneb** [comment]
@ShogunPanda before merging can you please link it to the issue?

**Comment by ShogunPanda** [comment]
Absolutely. I will in the next hour.

**Pull request merged**
