### PR TITLE
Updated the lru-cache to v7.4.0 migrated the deprecated methods

### LINKED ISSUE #117: lru-cache to v7.4.0 and remove deprecated `maxAge` option
Dependabot is failing to upgrade the `lru-cach` library from 6.0.0 to 7.4.0 because the tests fail.
Check the failing PR here: https://github.com/nearform/get-jwks/pull/116

### PR DESCRIPTION
**Pull request by radomird**
Closes #117

### CODE REVIEW

**Review by simoneb — APPROVED** [review]
LGTM. We need to release a major version

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by simoneb** [comment]
@radomird you have admin access, can you set up your personal npm and optic tokens and release a major once this is merged?

**Comment by radomird** [comment]
Yes, I'm on it.

**Pull request merged**
